h = "  Happy Programming!"
print("a"in h)
print("amp"in h)
print("\n\n####################\n\n")
x = "01::12::ab::&&"
y = x.split("::")
print(y)
print(", ".join(y))
print("##".join(y))
print("$$".join(y))
print("\n\n####################\n\n")
y = x.split(":")
print(y)
print(", ".join(y))
print("##".join(y))
print("$$".join(y))
